image:
  file: .gitpod.Dockerfile

tasks:
  - init: |
      echo "Hello $(gp url)"
      
  - name: Start Rendering Host
    init: npm install --prefix ./src/sxastarter
    command: npm run start:connected --prefix ./src/sxastarter
ports:
  - name: Rendering Host
    description: Rendering Host public port
    port: 3000
    onOpen: open-browser   
    visibility : public

vscode:
  extensions:
    - ms-vscode.powershell-preview
