image:
  file: .gitpod.Dockerfile

tasks:
  - name: e2e Tests
    command: |
      workspace_url=$(gp url)
      export PUBLIC_URL="${workspace_url/https:'//'/https://"3000-"}"

  - name: Start Rendering Host
    init: npm install --prefix ./src/sxastarter
    command: npm run start:connected --prefix ./src/sxastarter
ports:
  - name: Rendering Host
    description: Rendering Host public port
    port: 3000
    onOpen: open-browser   
    visibility : public

vscode:
  extensions:
    - ms-vscode.powershell-preview
