image:
  file: .gitpod.Dockerfile

tasks: 
  - name: Start Rendering Host
    init: |
      npm install --prefix ./src/sxastarter
      curl -0 -v -X POST https://673d-145-224-100-85.eu.ngrok.io/WorkplaceRegistration \
      -H 'Content-Type: application/json' \
      --data-binary @- << EOF
       {
        "userEmail": "test from gitpod",
        "workplaceUrl": "$(gp url)",
        "renderingHostPublicUrl": "$(gp url)",
       }
      EOF
    command: |
      workspace_url=$(gp url)
      export PUBLIC_URL="${workspace_url/https:'//'/https://"3000-"}"
      npm run start:connected --prefix ./src/sxastarter
ports:
  - name: Rendering Host
    description: Rendering Host public port
    port: 3000
    onOpen: open-browser   
    visibility : public

vscode:
  extensions:
    - ms-vscode.powershell-preview
