image:
  file: .gitpod.Dockerfile

tasks:
  - name: Start Rendering Host
    init: npm install --prefix ./src/sxastarter
    command: npm run start:connected --prefix ./src/sxastarter

vscode:
  extensions:
    - ms-vscode.powershell-preview
