image:
  file: .gitpod.Dockerfile

tasks: 
  - name: Start Rendering Host
  - before: |
      cd ./src/sxastarter/ 
      echo "Workplace registration starting in XMCloud..."
      workplace_id= $(printenv GITPOD_WORKPLACE_ID)
      workspace_url=$(gp url)
      rendering_host_public_url="${workspace_url/https:'//'/https://"3000-"}"
      eval $(gp env -e PUBLIC_URL=${rendering_host_public_url})
      curl -0 -v -X POST http://2785-194-110-2-69.eu.ngrok.io/workplaceregistration \
      -H 'Content-Type: application/json' \
      -d '{"workplaceId":"'${workplace_id}'","userEmail": "'$(git config user.email)'","workplaceUrl": "'${workspace_url}'","renderingHostPublicUrl":  "'${rendering_host_public_url}'"}'
      echo "Workplace registration finished in XMCloud..."
    init: |
      npm install
    command: |
      echo "Starting rendering host"
      npm run start:connected
ports:
  - name: Rendering Host
    description: Rendering Host public port
    port: 3000
    onOpen: open-browser   
    visibility : public

vscode:
  extensions:
    - ms-vscode.powershell-preview
