image:
  file: .gitpod.Dockerfile

tasks: 
  - name: Start Rendering Host
  - before: |
      cd ./src/sxastarter/ 
      echo "BEFORE TASK"
    init: |
      npm install
      workspace_url=$(gp url)
      rendering_host_public_url="${workspace_url/https:'//'/https://"3000-"}"
      eval $(gp env -e PUBLIC_URL=${rendering_host_public_url})
      curl -0 -v -X POST http://673d-145-224-100-85.eu.ngrok.io/WorkplaceRegistration \
      -H 'Content-Type: application/json' \
      -d '{"userEmail": "'$(git config user.email)'","workplaceUrl": "'${workspace_url}'","renderingHostPublicUrl":  "'${rendering_host_public_url}'"}'
    command: |
      npm run start:connected
ports:
  - name: Rendering Host
    description: Rendering Host public port
    port: 3000
    onOpen: open-browser   
    visibility : public

vscode:
  extensions:
    - ms-vscode.powershell-preview
