image:
  file: .gitpod.Dockerfile

tasks: 
  - name: Start Rendering Host
  - before: |
      cd ./src/sxastarter/ 
      echo "Workspace registration starting in XMCloud..."
      workspace_id= printenv GITPOD_WORKSPACE_ID
      workspace_url=$(gp url)
      rendering_host_public_url="${workspace_url/https:'//'/https://"3000-"}"
      eval $(gp env -e PUBLIC_URL=${rendering_host_public_url})
      curl -0 -v -X POST https://bd64-194-110-2-69.eu.ngrok.io/WorksplaceRegistration \
      -H 'Content-Type: application/json' \
      -d '{"workspaceId":"'${workspace_id}'","userEmail": "'$(git config user.email)'","workspaceUrl": "'${workspace_url}'","renderingHostPublicUrl":  "'${rendering_host_public_url}'"}'
      echo "Workspace registration finished in XMCloud..."
    init: |
      npm install
    command: |
      echo "Starting rendering host"
      npm run start:connected
ports:
  - name: Rendering Host
    description: Rendering Host public port
    port: 3000
    onOpen: open-browser   
    visibility : public

vscode:
  extensions:
    - ms-vscode.powershell-preview
